AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - '*.gemspec'
    - 'gemfiles/*'
    - Rakefile
    - Gemfile

Metrics/LineLength: 
  Max: 100
  Exclude:
    - 'test/**/*'

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false
