AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - '*.gemspec'
    - 'gemfiles/*'
    - Rakefile
    - Gemfile

Metrics/LineLength: 
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/FileName:
  Enabled: false
