AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  Exclude:
    - "*.gemspec"
    - "gemfiles/*"
    - "vendor/**/*"
    - Rakefile
    - Gemfile
require:
  - rubocop-performance
  - rubocop-minitest

Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false

Naming/FileName:
  Enabled: false

Layout/LineLength:
  Enabled: false
Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true

Style/WordArray:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
