name: Coverage
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        ruby: [3.0]
    runs-on: ubuntu-latest
    name: coverage
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: bundle install
        run: bundle install --jobs 4 --retry 3
      - uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: 6b81e393ea6ad38560386f650ea2fb0e57a7beb5e20f8c8364fabee30d5bff07
        with:
          coverageCommand: bundle exec rake
