name: Coverage

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: write
  contents: read

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake
      - uses: qltysh/qlty-action/coverage@v2
        with:
          oidc: true
          files: coverage/.resultset.json
